### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/themeisle-companion#255]
@andreilupu @selul we need to make sure we have proper checks in place to avoid this :( 

https://www.dropbox.com/s/47iucu2prs2ihwq/Screenshot%202018-06-20%2011.37.34.png?dl=0

**Comment by andreilupu** [comment]
@ineagu how old is the WordPress instance? OrbitFox requires at least 4.7

But I agree that it should fail gracefully and we should not load anything when the requirements are not fulfilled( aka PHP >5.3 and WP >4.7)

**Comment by ineagu** [comment]
Is older I think, still we should show some notice and not break the install

**Comment by selul** [comment]
normally it's very unlikely to get that error as a user of our plugin. Usually, they install the plugin from wordpress.org, directly from WordPress dashboard. If they have an older WP or PHP version, incompatible with our plugin, WordPress won't let them install the plugin.

It was happening for you because you installed it using the zip.

Although we can make some graceful bail if the environment is not safe to run, I won't consider this is a priority for now @andreilupu.

**Comment by ineagu** [comment]
I have installed it from wp dashboard, not zip.

W.org hide the plugin only if php is lower, they let you install if your wp version doesn’t support it.

**Comment by contactashish13** [comment]
@ineagu On WP 4.5/PHP 7 I installed from the wp dashboard and activated all modules but I still did not get this fatal error. Can you list down the steps for this?

**Comment by ineagu** [comment]
I don't have the instance for now, I guess it was a much older wp version, we can close it for now if 4.5 works ok
