### ISSUE TITLE
Gutenberg blocks module

### ISSUE THREAD

**Issue by selul** [Codeinwp/themeisle-companion#260]
| Block  | Examples|
| ------------- | ------------- |
| Pricing Table  | -  |
| Our Services  | -  | 
| Contact form  | -  | 
| Spacer  | -  | 
| Testimonials | -  | 
| Post Grid | https://atomicblocks.com/block-party-check-out-the-new-post-grid-block/  |
| Collapsable Content| -  |  
| Sharing Icons Block| -  | t| -  | 
| Plugin Card  | Advanced Gutenberg Blocks  |
| Woo Product Card  | Advanced Gutenberg Blocks  |
| Google Map  | Advanced Gutenberg Blocks  |
| Notice  | Advanced Gutenberg Blocks  |
| Click to tweet   | coblocks  |
| About Author  | coblocks  |
| Chart ( Just 1 chart type, pie chart ) | -  |

Some thoughts: 
 * We should aim for minimum css and let themes overwrite it, avoid using jquery, font-awesome , as a real use-case for those.
 * We don't need to reinvent them, the examples can be used as good patterns which we can develop ours. 

Use case: 

- Duplicate a post from codeinwp blog which include a plugin box, chart and tweet this, use theme css to make it look like real site.
- Create a page on hestia using gutenberg blocks which look exactly like the homepage ( use custom css if needed)

**Comment by andreilupu** [comment]
Ok, I've formed a vision for this module and I've started to work actively on it, first on the simple blocks.

Now I'll dump some ideas here just to keep track of things:

1) The **Spacer** block falls since there is already a cool one in Gutenberg already.

2) I think that we shouldn't do the WooCommerce block since this one exists https://wordpress.org/plugins/woo-gutenberg-products-block.

3) For the Google maps block, I would love to get inspired from here https://github.com/pantheon-systems/google-map-gutenberg-block.

4) I will try to add a minimal style for each block, but I'm also curious what is the general idea about this https://github.com/WordPress/gutenberg/pull/7362

5) It would be nice to have a set of distinct SVG icons, personalized in the OrbitFox style, for each block.

**Comment by ineagu** [comment]
@andreilupu @selul just a short feedback on the WooCommerce block approach, I guess you are right, if that block would get in WooCommerce plugin, then we can assume that a person interested in an e-commerce landing page would either have woo pre-installed or we would just trigger woo installation.

My idea was that we won't want to recommend/rely on separate block plugins for our further templates, however official woo plugin seems to be one that we can rely on.

**Comment by selul** [comment]
@andreilupu thanks for the heads-up. 
I agree with 1,2,3 as for 4 looks very interesting but for now, we can keep just the minimal style. 

As for the icons, yes, we can tackle them in the final step, before the release.

**Comment by abaicus** [comment]
Hey @andreilupu,

I've tested the blocks and here are a few things that seem to not work as expected or issues:

- [ ] Font Awesome Icon Block - icon cannot be changed and size / alignment don't affect the front end in any way;
- [ ] Sharing icons could have an option to display them on one line or stacked as they are now (essentially adding a class would be good);
- [ ] Services block (beta) - doesn't seem to take into account how many columns I select. Always 
will display the same thing on the front end. Sometimes part of the content seems to disappear randomly;
- [ ] Pricing tables - same as services block. Also, can you set the alignment to center by default in the sub-blocks? 
- [ ] Plugin Card - links display as raw HTML on the front end;
- [ ] Testimonial Block - testimonial photo isn't displayed. Allow alignment of content;
- [ ] Posts grid - different markup front end / editor. Add post excerpt maybe. A read more button - See the OBFX Elementor post grid for a better example than I can write here.
- [ ] Chart Block - throws notice on front end;
- [ ] Pricing box block should be deleted, i guess;

I also get a lot of block validation errors in the console if I publish the page and come back to the editor. 
💃

**Comment by andreilupu** [comment]
@abaicus I've fixed some issues from the list.

For the blocks with columns, I created only some experimental CSS but I will need your help to create a stable style for Services/Pricings and Posts Grid. In front-end, there is a class that is working and it provides the number of columns.

Pricing box block is still an alternative of creating columns in case we fail to create a grid by this layout.

The notices from Chart Block are coming from Gutenberg since atm, there is no way to set a default for array, it is still wip.

And the testimonial block, we need to decide what to align, content, tite, name, picture.

I'm going to enrich the post grid with some options.

**Comment by selul** [comment]
@HardeepAsrani as we spoke on slack can you check here the current progress with the blocks and let me know if we can do some improvements to the ui/options in order to release this module, maybe this week ? 

I think the backend logic is pretty strong, however from what I have played with them, there is not much use for them in the current shape, at least from the design point of view. 

If you have any troubles in understanding something, @andreilupu might help you as he wrote them until now. 

You can check the block list in my first comment.

**Comment by HardeepAsrani** [comment]
Sure, I'll take a look. The one I saw so far seems good. By the way @andreilupu, **lodash** is available in core now with Gutenberg, so you can just add them to dependency when enqueuing script.

**Comment by rodica-andronache** [comment]
Tested a bit OBFX and saw this notice after editing the chart block https://prnt.sc/l3wu82.
and this was the pricing block in customizer https://prnt.sc/l3wv3k and on the site https://prnt.sc/l3wvaj

**Comment by HardeepAsrani** [comment]
@rodica-andronache Can you explain the other two issues? And are Font Awesome not being loaded? Can you check in the source of page?

**Comment by rodica-andronache** [comment]
for the pricing block, the problems I saw are that in customizer, that " Add text or type/ to add content " was appearing in the actual block, and on the site, the icons are not showing up even though it seems that FA is loaded. I tested with Astra, in case is something to do with this

**Comment by HardeepAsrani** [comment]
@rodica-andronache That's not an issue. People can add other stuff inside it too. I'll check the font awesome issue.

The first issue is really weird as it was happening when I started to develop the block. Then it didn't happen for weeks until today.

**Comment by HardeepAsrani** [comment]
@rodica-andronache Works for me. Could be possible that some plugin is loading Font Awesome 4.x, can you check?

**Comment by rodica-andronache** [comment]
@HardeepAsrani for the FA issue, it seems it's because of Elementor, once I deactivated that, the icons appeared.

**Comment by radu-themeisle** [comment]
- [ ] integrate styling for hr (used in pricing block) and make sharing buttons full width on mobile

**Comment by contactashish13** [comment]
@HardeepAsrani can this be closed now?
