### ISSUE TITLE
Menu icons not vertically aligned

### ISSUE THREAD

**Issue by radu-themeisle** [Codeinwp/themeisle-companion#314]
I used the menu icons module here https://demo.themeisle.com/neve-charity/ and the icons are not vertically aligned to the middle. Deactivating the property from the icon doesn't seem to have an effect. Instead, if you put the property on the :before of the icon, it has effect.
It seems that the baseline property would work but only if you use the -webkit-baseline-middle, which is not the best solution.

https://www.dropbox.com/s/dgs17vdts2i4c6j/image.jpg?dl=0

**Comment by stefan-cotitosu** [comment]
@radu-themeisle I can't find a solution here.

Each theme aligns menu items and icons differently. 
Either with 
```
display: inline-block;
vertical-align: middle;
``` 
or
```
display: flex;
align-items: center;
```

Also, each theme has a unique identifier for the primary menu and a different one for the Very Top Bar ( I thought that I can use the menu classes ). 
Some of them have style for dashicons others for font-awesome icons.

From previous discussions on similar topics, I understood that is not a good approach to add compatibility with many plugins in the theme. I really think that this issue should be fixed in Neve and not in the plugin.

Here is how the menu looks on 4 different themes, with no style from the Menu Icons module.
Each menu has pairs of items with similar icons, the left one from dashicons, the right one from font-awesome.
For me, it seems impossible to make them look the same from the plugin.

### Hestia
<img width="670" alt="hestia-menu-icons" src="https://user-images.githubusercontent.com/26867648/49942680-ac3ab400-feee-11e8-8792-b974814574c6.png">

### Neve
<img width="731" alt="neve-menu-icons" src="https://user-images.githubusercontent.com/26867648/49942696-b5c41c00-feee-11e8-8723-c64d7c743268.png">

### Astra
<img width="654" alt="astra-menu-icons" src="https://user-images.githubusercontent.com/26867648/49942704-bd83c080-feee-11e8-899d-c7b9fdab154c.png">

### OceanWP
<img width="744" alt="oceanwp-menu-icons" src="https://user-images.githubusercontent.com/26867648/49942709-c1afde00-feee-11e8-902d-b5559464bcdd.png">

Any thoughts? 😄
