### ISSUE TITLE
Contact form issue

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/themeisle-companion#339]
@selul @contactashish13 We have an issue here with the contact form from the OrbitFox page https://orbitfox.com/contact/

I have sent the message with success: 
![screenshot 2019-02-06 at 17 21 11](https://user-images.githubusercontent.com/6906834/52351556-b337fb80-2a33-11e9-96f1-512686eb2d33.png)

we received the message on HS, I replied and I don't receive the message in my email because we're trying to send it to the wrong email. 

If we reply to the email, the message will go friends@orbitfox.com instead to the customer email (in this example madalin@themeisle.com) 

Please see the image attached: 

![screenshot 2019-02-06 at 17 23 07](https://user-images.githubusercontent.com/6906834/52352133-baabd480-2a34-11e9-8ffc-209878bd7127.png)

The only way to reply right now to these messages is by creating a new ticket and copy-paste the customer email.

**Comment by contactashish13** [comment]
@mileamadalin I think this is related to https://github.com/Codeinwp/themeisle-content-forms as that creates the contact form. It looks like this is a problem with HS as the code correctly adds a **reply-to** header which HS removes. 

One way to test this and to ascertain that the problem is with HS is to add another contact form widget and change its **send-to** to a gmail ID. Once you receive the email, try to reply and it should populate the correct **reply-to** address.

**Comment by mileamadalin** [comment]
@contactashish13 I think the problem is from the OrbitFox contact form since this one is the only Mailbox from HS with the problem. The others, ReviveSocial, Optimole, Themeisle, are working well. I can try to do this as well. Can we please check if we use the same details on Optimole webiste as we do on Orbitfox?

**Comment by contactashish13** [comment]
@mileamadalin I have no access to either so I won't be able to check the settings.

**Comment by mileamadalin** [comment]
@contactashish13 I don't have access either @selul could you please help here?

**Comment by mileamadalin** [comment]
@contactashish13 Close this one. Fixed
