### ISSUE TITLE
Post Grid - Style \ Content tab appears blank

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/themeisle-companion#346]
On a Neve Starter site https://demo.themeisle.com/neve-charity noticed that the content styles tab appear blank, thus leaving no options for styling customization of the title, excerpt etc.

Thanks!

![screenshot_2019-04-03_at_17 24 53](https://user-images.githubusercontent.com/4193672/55709653-77002780-59f1-11e9-9373-314bf76ed3d6.png)

**Comment by rodica-andronache** [comment]
@JohnPixle I just realized, the tab appears blank because the content is hidden here https://prnt.sc/ngnql2 so there is no content displayed, for which to add style.
The title's style can be changed from Style -> Title.

But indeed the Grid could offer more customization options, that we could use in the starter sites. I'll create a new issue with suggestions, where you can add your own as well.
