### ISSUE TITLE
[WP 5.6]Add/edit post doesn't work when Gutenberg is installed

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/themeisle-companion#563]
When both `Gutenberg` and` Orbit Fox` are installed and activated, when you try to `edit or add a new post`, that's not possible.
An error is thrown in the console.
![download](https://user-images.githubusercontent.com/3266155/97997958-34cbe180-1df2-11eb-8e44-5006a204e2d7.png)

Can be seen here
```
https://established-natterjack.jurassic.ninja/wp-admin/
user: demo
pass: p0Z@m3jibC58)qID@zKhjH!8
```

**Comment by cristian-ungureanu** [comment]
@rodica-andronache I can't replicate it anymore with the latest Gutenberg version and WP 5.6-RC3-49749. Can you have another look, please?

**Comment by rodica-andronache** [comment]
@cristian-ungureanu you can see it here
```
https://selfish-gamefowl.jurassic.ninja/
demo
MCY(&U)0p4nu$UpehU$Hgl$P
```

**Comment by cristian-ungureanu** [comment]
@rodica-andronache it seems like the problem comes from the Gutenberg Blocks module. That module gets its code from https://github.com/Codeinwp/gutenberg-blocks as a composer package. The errors were fixed in gutenberg-blocks but we didn't update OrbitFox after. The error will be fixed when we release a new version of OrbitFox and the composer package will update to the latest version.
