### ISSUE TITLE
[WP 5.8] Deprecated function notice when creating new post with the wp 5.8 update

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/themeisle-companion#699]
When i try to create a new post with the wp 5.8 update, i get this notice:

[05-Jul-2021 08:50:05 UTC] PHP Deprecated:  block_categories is <strong>deprecated</strong> since version 5.8.0! Use block_categories_all instead. in /defiantmilk/wordpress/wp-includes/functions.php on line 5458

**Plugin version:** 2.10.6
**Wordpress version:** 5.8-RC1

**Comment by irinelenache** [comment]
These warnings are thrown when i open the customizer https://vertis.d.pr/1Q8v1b
(If i have otter blocks activated instead of obfx, no warning is thrown)

**Comment by cristian-ungureanu** [comment]
Those issues are happening because of the gutenberg-blocks composer package. I saw that @HardeepAsrani made an update for that so this should be fixed after we release a new Obfx version.
Saw that the check here https://github.com/Codeinwp/gutenberg-blocks/blob/master/inc/class-main.php#L128 is with 5.8 version so if you will test this with the RC version, the errors will still be there.

@HardeepAsrani maybe we can change that with something like this https://github.com/Codeinwp/neve-pro-addon/pull/1456/commits/9b4646573c0b0bdc17c249a18662af1f13be8387#diff-404caad1b51f343a77752110e14e3bca358f8318424e2eb519c2dd4b15b3d34aR38

**Comment by cristian-ungureanu** [comment]
@irinelenache this should be fixed too but we're gonna wait a bit for wp 5.8 to be released. When that will happen, the errors won't appear anymore.
To test the fixes for this, grab the development branch from this repo and run in the terminal "yarn install", "composer install", "yarn run build".
Maybe have a look at this when wp 5.8 is released.

**Comment by HardeepAsrani** [comment]
@cristian-ungureanu Given that it's just few days away, no sense in releasing a version just to fix the issue with RC version. 😛

**Comment by irinelenache** [comment]
@cristian-ungureanu followed your steps and i didn't get any error/notice 🚀
