### ISSUE TITLE
OrbitFox dashboard to react App

### ISSUE THREAD

**Issue by abaicus** [Codeinwp/themeisle-companion#707]
Let's transform the current OrbitFox dashboard to a react app.

We can start from the current Neve options page. 

- The **Available Modules** tab is really similar to the Neve Pro modules tab we already have
- The **Recommended Plugins** tab mostly has the same functionality we already have in the 

### Steps to follow:

- [x] Bootstrap the application using the WordPress scripts package for bundling the JS/CSS;
- [x] Pass the initialization data (modules options, plugins states, and anything else that we might need) through localization;
- [x] Save them in the application context on initialization and make sure to use that further in the app. This way we can have data consistency while switching tabs (e.g. after you install a plugin and switch tabs, the state should be maintained);
- [x] `obfx_data` is the WordPress option where all the options from this page are saved;
- [x] Let's make sure that we have the basic functionality going first and then we'll tweak the design as needed. For now, let's simply follow the same design we have in Neve;

_As this will involve some kind of global state management, we should use react context to store everything for the page._

**Comment by arinaturcu** [comment]
The main functionality of the plugin is done and I tried to follow the same design as in the Neve dashboard. I need some review on the code and the design, maybe @cristian-ungureanu can do it.
Here is a demo site with the plugin installed: https://endurablewing.tastewp.com/
username: arina
password: u3qEvujNTpY

**Comment by cristian-ungureanu** [comment]
Hey @arinaturcu, I'm checking it right now. I'll let you know if I find something.

**Comment by cristian-ungureanu** [comment]
@irinelenache can you please test this feature? I was a bit too excited and already merged this into the development branch, I forgot it needs testing too.

So, here's the testing scenario:

1. Download the build from https://github.com/Codeinwp/themeisle-companion/pull/713
2. Have two TasteWP instances, one with the new dashboard, one with the old one.
3. Compare the two instances, they should have the same modules and the same behavior.
4. Try having this version of obfx: https://github.com/Codeinwp/themeisle-companion/releases/tag/v2.10.6, enable all modules ( even the retired ones ) and check the testing scenarios from https://github.com/Codeinwp/themeisle-companion/pull/703 and https://github.com/Codeinwp/themeisle-companion/pull/705

**Comment by irinelenache** [comment]
@cristian-ungureanu I tried testing the new dashboard but it doesn't work for me in a tastewp instance. When i try to open obfx general settings, i get these warnings and nothing is visible (https://vertis.d.pr/eO6pMp):
```
Warning:  include(/horribleminister/wordpress/wp-content/plugins/themeisle-companion/dashboard/build/dashboard.asset.php): failed to open stream: No such file or directory in /horribleminister/wordpress/wp-content/plugins/themeisle-companion/core/app/class-orbit-fox-admin.php on line 170
Warning:  include(): Failed opening '/horribleminister/wordpress/wp-content/plugins/themeisle-companion/dashboard/build/dashboard.asset.php' for inclusion (include_path='.:/usr/share/php') in /horribleminister/wordpress/wp-content/plugins/themeisle-companion/core/app/class-orbit-fox-admin.php on line 170
Warning:  include(/horribleminister/wordpress/wp-content/plugins/themeisle-companion/dashboard/build/dashboard.asset.php): failed to open stream: No such file or directory in /horribleminister/wordpress/wp-content/plugins/themeisle-companion/core/app/class-orbit-fox-admin.php on line 209
Warning:  include(): Failed opening '/horribleminister/wordpress/wp-content/plugins/themeisle-companion/dashboard/build/dashboard.asset.php' for inclusion (include_path='.:/usr/share/php') in /horribleminister/wordpress/wp-content/plugins/themeisle-companion/core/app/class-orbit-fox-admin.php on line 209

```

Can be checked here:
```
 Admin area URL: https://horribleminister.tastewp.com/wp-admin 
 Username: irinel 
 Password: 5-pEhRMXdJw 
```

**Comment by abaicus** [comment]
@irinelenache there was an issue with the github workflow that builds the files. I fixed it. The zip should work now 🚀

**Comment by cristian-ungureanu** [comment]
@irinelenache Andrei managed to fix the build, it should work fine now.

**Comment by irinelenache** [comment]
@cristian-ungureanu @abaicus @arinaturcu  Now the zip works fine 🙏 
Nice work overall 🚀 Tested and found a few things:

- [ ] The old dashboard had a **confirmation message** (https://vertis.d.pr/WcD0Kk) after saving a setting and this is not present in the new one. It can be positioned closer to the Save button because as you can see in the video, i had to scroll a bit to see it and it was visible for a short time.
- [ ] In the **Policy notice** settings, the single quote character appears as `&#039;`
old: https://d.pr/1B6O38
new: https://d.pr/urkLJJ
- [ ] I can't delete the **Policy button label** and **Accept cookies button label** inputs so i can write something else https://vertis.d.pr/harDVm
- [ ] The **external links** (https://vertis.d.pr/uAjwYq) should have the icon associated like in the Neve dashboard(https://vertis.d.pr/RqfVuo)?

After switching from **obfx 2.10.6** to this version, some activated modules appear as deactivated (Template directory, mystock, menu icons, header/footer scripts) even if they still work in frontend. Also, only this notice https://vertis.d.pr/Ky9mKR was present after switching. (No notice for **Uptime monitor**). 
For the **Analytics integration**, i had a tracking code selected which doesn't appear as selected anymore and can't select it.

**Comment by arinaturcu** [comment]
@irinelenache Thank you for the feedback! The issues you found should be fixed now. Let me know if I missed anything.
The zip is [here](https://github.com/Codeinwp/themeisle-companion/pull/714)

**Comment by irinelenache** [comment]
@arinaturcu The new fixes work as expected 👍 Found only a small thing:

- [ ] The gutenberg blocks notification's html isn't rendered https://vertis.d.pr/VVdAyJ
