### ISSUE TITLE
Update Twitter icon/name

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/themeisle-companion#836]
### What problem does this address?

A user asked about updating the Twitter icon and name in the social sharing module:
<img width="918" alt="image" src="https://github.com/Codeinwp/themeisle-companion/assets/86592992/84700a0f-afd9-4c0e-bcb7-6d85db8fe3ed">

https://secure.helpscout.net/conversation/2539624941/409037?viewId=931544
### What is your proposed solution?

Update the icon and name.

### Will this feature require documentation? (Optional)

None

**Comment by Soare-Robert-Daniel** [comment]
One problem here is that for the social module, we use this lib https://github.com/ericakfranz/socicon to display the icons. The problem is that lib is not updated anymore, so it does not have the latest icon for X/Twitter.

I suggest using Font Awesome directly. So we will need to remove the deps on Socicon and update FA to the latest version.

**Comment by Soare-Robert-Daniel** [comment]
One problem here, the latest version of Socicon does not have the new Twitter logo. The FA version is missing some Chinese brands, like Baidu, which we have available to use.

Socicon repo: https://github.com/Ybbet/socicon/tree/main
FA6 brands: https://fontawesome.com/search?o=r&f=brands



![Image](https://github.com/Codeinwp/themeisle-companion/assets/17597852/f0f86b27-1c03-4a71-ab39-52b447c9a35d)

**Comment by Soare-Robert-Daniel** [comment]
[UPDATE] The new X icon has been introduced in the font: https://github.com/Ybbet/socicon/issues/9
